# Generated by Django 4.0.6 on 2022-08-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('pub_date', models.DateField()),
                ('upload_berkas', models.FileField(upload_to='')),
                ('kategori', models.ManyToManyField(to='home.category')),
                ('penulis', models.ManyToManyField(to='home.autor')),
            ],
        ),
    ]
